language: node_js
node_js:
  - "8.9.4"
before_install:
  - "npm install -g bower"
  - "bower install"
  - "npm install -g web-component-tester"
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
script: "wct"
