language: node_js
node_js: stable
deploy:
  provider: pages
  skip-cleanup: true
  github-token: EfAFVfGI16t61RoPpDs6kA
  keep-history: true
  on:
    branch: develop
install:
  - npm install -g polymer-cli
  - npm install
  - polymer install
before_script:
  - npm run lint
script:
  - xvfb-run npm run test
  - xvfb-run npm run test:integration
