language: node_js
node_js: stable
deploy:
  provider: pages
  skip-cleanup: true
  github-token: EfAFVfGI16t61RoPpDs6kA
  keep-history: true
  on:
    branch: develop
before_script:
- npm install bower
- export PATH=$PWD/node_modules/.bin:$PATH
